#!/usr/bin/env python3
"""Ingest local threat-intelligence corpora into Qdrant.

Currently supports:
- MITRE ATT&CK JSONL generated by scripts/build_mitre_rag.py

Usage:
    python3 scripts/ingest_threat_intel.py --source mitre_attack
    python3 scripts/ingest_threat_intel.py --source all
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

from src.rag import VectorStore

ROOT = Path(__file__).parent.parent
DEFAULT_CONFIG = ROOT / "configs" / "default.yaml"
MITRE_JSONL = ROOT / "data" / "mitre_attack" / "rag_documents" / "techniques.jsonl"


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def load_jsonl(path: Path) -> tuple[list[str], list[dict[str, Any]], list[str]]:
    documents: list[str] = []
    metadatas: list[dict[str, Any]] = []
    ids: list[str] = []

    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            payload = json.loads(line)
            ids.append(str(payload["id"]))
            documents.append(str(payload["text"]))
            metadatas.append(dict(payload.get("metadata") or {}))

    return documents, metadatas, ids


def ingest_mitre_attack(store: VectorStore) -> int:
    if not MITRE_JSONL.exists():
        raise FileNotFoundError(
            f"MITRE JSONL not found at {MITRE_JSONL}. Run scripts/build_mitre_rag.py first."
        )

    documents, metadatas, ids = load_jsonl(MITRE_JSONL)
    for metadata in metadatas:
        metadata.setdefault("source", "mitre_attack")
        metadata.setdefault("corpus", "mitre_attack")

    return store.add_documents(documents=documents, metadatas=metadatas, ids=ids)


def main() -> None:
    parser = argparse.ArgumentParser(description="Ingest threat intelligence into Qdrant")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG), help="Path to config YAML")
    parser.add_argument(
        "--source",
        default="all",
        choices=["all", "mitre_attack"],
        help="Corpus to ingest",
    )
    args = parser.parse_args()

    config = load_config(Path(args.config))
    rag_config = dict(config.get("rag") or {})

    store = VectorStore(rag_config)
    store.initialize()

    ingested = 0
    if args.source in {"all", "mitre_attack"}:
        count = ingest_mitre_attack(store)
        ingested += count
        print(f"Ingested MITRE ATT&CK documents: {count}")

    print(f"Done. Collection '{store.collection_name}' now has ~{store.document_count} documents.")


if __name__ == "__main__":
    main()
